"""bug fix

Revision ID: b73e99fe27f9
Revises: 
Create Date: 2023-06-28 11:53:30.084413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b73e99fe27f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_application', schema=None) as batch_op:
        batch_op.drop_constraint('loan_application_loan_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'loan', ['loan_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_application', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('loan_application_loan_id_fkey', 'loan', ['loan_id'], ['id'])

    # ### end Alembic commands ###
