"""enum fix

Revision ID: 295f5c9d9482
Revises: d31579797d50
Create Date: 2023-06-30 20:39:11.828533

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '295f5c9d9482'
down_revision = 'd31579797d50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_profile', schema=None) as batch_op:
        batch_op.alter_column('employment_status',
               existing_type=postgresql.ENUM('EMPLOYED', 'SELF_EMPLOYED', 'UNEMPLOYED', name='employmentstatus'),
               type_=sa.Enum('EMPLOYED', 'UNEMPLOYED', 'SELF_EMPLOYED', name='employmentstatus'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_profile', schema=None) as batch_op:
        batch_op.alter_column('employment_status',
               existing_type=sa.Enum('EMPLOYED', 'UNEMPLOYED', 'SELF_EMPLOYED', name='status'),
               type_=postgresql.ENUM('EMPLOYED', 'SELF_EMPLOYED', 'UNEMPLOYED', name='employmentstatus'),
               existing_nullable=False)

    # ### end Alembic commands ###
