"""fix constraint

Revision ID: bc46b0212d66
Revises: 295f5c9d9482
Create Date: 2023-06-30 21:32:57.369761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc46b0212d66'
down_revision = '295f5c9d9482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_assessment_report', schema=None) as batch_op:
        batch_op.drop_constraint('risk_assessment_report_borrower_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'financial_profile', ['borrower_id'], ['borrower_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_assessment_report', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('risk_assessment_report_borrower_id_fkey', 'financial_profile', ['borrower_id'], ['id'])

    # ### end Alembic commands ###
