"""making changes

Revision ID: 0e7b9b2975dd
Revises: 3b8d366b4900
Create Date: 2023-07-03 12:51:05.187232

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0e7b9b2975dd'
down_revision = '3b8d366b4900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wallet_id', sa.UUID(), nullable=True))
        batch_op.create_unique_constraint(None, ['wallet_id'])
        batch_op.drop_column('transaction_history')
        batch_op.drop_column('wallet_balance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wallet_balance', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('transaction_history', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('wallet_id')

    # ### end Alembic commands ###
